"""Alembic script template."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4affa9afcee"
down_revision: str | None = None
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('osm_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('standard_checkup_price_usd', sa.Double(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('accepted_specialties', sa.Text(), nullable=True),
    sa.Column('average_wait_minutes', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Double(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('is_network_partner', sa.Boolean(), nullable=False),
    sa.Column('opening_hours_json', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('clinic_id'),
    sa.UniqueConstraint('osm_id')
    )
    op.create_table('doctors',
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('specialty', sa.Text(), nullable=True),
    sa.Column('clinic_name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('clinic_lat', sa.Double(), nullable=True),
    sa.Column('clinic_lon', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_table('groups',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('next_session_at', sa.DateTime(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('diagnosis_date', sa.Date(), nullable=True),
    sa.Column('primary_doctor_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['primary_doctor_id'], ['doctors.doctor_id'], ),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('appointments',
    sa.Column('appointment_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=True),
    sa.Column('clinic_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.clinic_id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('device_tokens',
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('medications',
    sa.Column('medication_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('generic_name', sa.Text(), nullable=True),
    sa.Column('schedule', sa.String(length=20), nullable=True),
    sa.Column('schedule_label', sa.Text(), nullable=True),
    sa.Column('dose_instruction', sa.Text(), nullable=True),
    sa.Column('eye', sa.String(length=10), nullable=True),
    sa.Column('prescribed_by', sa.String(length=36), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('refill_due_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescribed_by'], ['doctors.doctor_id'], ),
    sa.PrimaryKeyConstraint('medication_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=True),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sender_name', sa.Text(), nullable=True),
    sa.Column('sender_avatar_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('pressure_readings',
    sa.Column('reading_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('value_mmhg', sa.Double(), nullable=False),
    sa.Column('eye', sa.String(length=10), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('device', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reading_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('dose_logs',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('medication_id', sa.String(length=36), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.medication_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('refill_alerts',
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('medication_id', sa.String(length=36), nullable=False),
    sa.Column('remind_on', sa.Date(), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.medication_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    # NOTE: _sqliteai_vector, migrations, access_tokens are pre-existing SQLite Cloud
    # system/platform tables — do NOT drop them.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: pre-existing system tables are not managed by Alembic.
    op.drop_table('refill_alerts')
    op.drop_table('dose_logs')
    op.drop_table('refresh_tokens')
    op.drop_table('pressure_readings')
    op.drop_table('messages')
    op.drop_table('medications')
    op.drop_table('device_tokens')
    op.drop_table('appointments')
    op.drop_table('alerts')
    op.drop_table('patients')
    op.drop_table('groups')
    op.drop_table('doctors')
    op.drop_table('clinics')
    # ### end Alembic commands ###
